resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/((username))/spring-music
    branch: hello

jobs:
- name: unit-test
  plan:
  - get: git-repo
    trigger: true
  - task: run-unit-test
    file: git-repo/ci/tasks/unit-test.yml
